// AUTO-GENERATED by scripts/fetch-edu-fundamentals.mjs — do not edit by hand.
// Source: SEC EDGAR companyfacts (public domain, US Government work). Bundled,
// reproducible fundamentals snapshot for the Market Wedge Finder DCF.
// FCF = operating cash flow − capital expenditure (annual 10-K).
// Snapshot asOf: 2026-06-15.

export interface AnnualFcf { fy: string; fcf: number } // fy = fiscal-year end "YYYY-MM-DD", fcf in USD
export interface Fundamentals {
  ticker: string;
  cik: number;
  name: string;
  sharesOutstanding: number;
  fcfHistory: AnnualFcf[]; // chronological, last ~6 fiscal years
}

export const FUNDAMENTALS_AS_OF = "2026-06-15";
export const FUNDAMENTALS_SOURCE = "SEC EDGAR (companyfacts, 10-K)";

export const FUNDAMENTALS: Fundamentals[] = [
  {
    "ticker": "AAPL",
    "cik": 320193,
    "name": "Apple Inc.",
    "sharesOutstanding": 14687356000,
    "fcfHistory": [
      {
        "fy": "2020-09-26",
        "fcf": 73365000000
      },
      {
        "fy": "2021-09-25",
        "fcf": 92953000000
      },
      {
        "fy": "2022-09-24",
        "fcf": 111443000000
      },
      {
        "fy": "2023-09-30",
        "fcf": 99584000000
      },
      {
        "fy": "2024-09-28",
        "fcf": 108807000000
      },
      {
        "fy": "2025-09-27",
        "fcf": 98767000000
      }
    ]
  },
  {
    "ticker": "KO",
    "cik": 21344,
    "name": "COCA COLA CO",
    "sharesOutstanding": 4302482418,
    "fcfHistory": [
      {
        "fy": "2020-12-31",
        "fcf": 8667000000
      },
      {
        "fy": "2021-12-31",
        "fcf": 11258000000
      },
      {
        "fy": "2022-12-31",
        "fcf": 9534000000
      },
      {
        "fy": "2023-12-31",
        "fcf": 9747000000
      },
      {
        "fy": "2024-12-31",
        "fcf": 4741000000
      },
      {
        "fy": "2025-12-31",
        "fcf": 5296000000
      }
    ]
  },
  {
    "ticker": "XOM",
    "cik": 34088,
    "name": "EXXON MOBIL CORP",
    "sharesOutstanding": 4144947162,
    "fcfHistory": [
      {
        "fy": "2020-12-31",
        "fcf": -2614000000
      },
      {
        "fy": "2021-12-31",
        "fcf": 36053000000
      },
      {
        "fy": "2022-12-31",
        "fcf": 58390000000
      },
      {
        "fy": "2023-12-31",
        "fcf": 33450000000
      },
      {
        "fy": "2024-12-31",
        "fcf": 30716000000
      },
      {
        "fy": "2025-12-31",
        "fcf": 23612000000
      }
    ]
  },
  {
    "ticker": "JPM",
    "cik": 19617,
    "name": "JPMORGAN CHASE & CO",
    "sharesOutstanding": 2679511418,
    "fcfHistory": []
  }
];

export function getFundamentals(ticker: string): Fundamentals | undefined {
  return FUNDAMENTALS.find((f) => f.ticker === ticker.toUpperCase());
}
