// AUTO-GENERATED by scripts/fetch-edu-prices.mjs — do not edit by hand.
// Source: Yahoo Finance public chart endpoint (monthly closes). Snapshot is a
// bundled, reproducible historical series for the Research Sandbox — the tool
// reshapes history into a counterfactual, so live prices are not required.
// Snapshot asOf: 2026-06-15.

export interface PricePoint { date: string; close: number } // date = "YYYY-MM"
export interface DemoAsset {
  ticker: string;
  name: string;
  note: string;
  currency: string;
  points: PricePoint[];
}

export const PRICES_AS_OF = "2026-06-15";
export const PRICES_SOURCE = "Yahoo Finance (public chart endpoint)";

export const DEMO_ASSETS: DemoAsset[] = [
  {
    "ticker": "AAPL",
    "name": "Apple Inc.",
    "note": "rate-sensitive growth (tech)",
    "currency": "USD",
    "points": [
      {
        "date": "2016-07",
        "close": 26.05
      },
      {
        "date": "2016-08",
        "close": 26.52
      },
      {
        "date": "2016-09",
        "close": 28.26
      },
      {
        "date": "2016-10",
        "close": 28.39
      },
      {
        "date": "2016-11",
        "close": 27.63
      },
      {
        "date": "2016-12",
        "close": 28.95
      },
      {
        "date": "2017-01",
        "close": 30.34
      },
      {
        "date": "2017-02",
        "close": 34.25
      },
      {
        "date": "2017-03",
        "close": 35.92
      },
      {
        "date": "2017-04",
        "close": 35.91
      },
      {
        "date": "2017-05",
        "close": 38.19
      },
      {
        "date": "2017-06",
        "close": 36.01
      },
      {
        "date": "2017-07",
        "close": 37.18
      },
      {
        "date": "2017-08",
        "close": 41
      },
      {
        "date": "2017-09",
        "close": 38.53
      },
      {
        "date": "2017-10",
        "close": 42.26
      },
      {
        "date": "2017-11",
        "close": 42.96
      },
      {
        "date": "2017-12",
        "close": 42.31
      },
      {
        "date": "2018-01",
        "close": 41.86
      },
      {
        "date": "2018-02",
        "close": 44.53
      },
      {
        "date": "2018-03",
        "close": 41.94
      },
      {
        "date": "2018-04",
        "close": 41.31
      },
      {
        "date": "2018-05",
        "close": 46.72
      },
      {
        "date": "2018-06",
        "close": 46.28
      },
      {
        "date": "2018-07",
        "close": 47.57
      },
      {
        "date": "2018-08",
        "close": 56.91
      },
      {
        "date": "2018-09",
        "close": 56.44
      },
      {
        "date": "2018-10",
        "close": 54.72
      },
      {
        "date": "2018-11",
        "close": 44.65
      },
      {
        "date": "2018-12",
        "close": 39.44
      },
      {
        "date": "2019-01",
        "close": 41.61
      },
      {
        "date": "2019-02",
        "close": 43.29
      },
      {
        "date": "2019-03",
        "close": 47.49
      },
      {
        "date": "2019-04",
        "close": 50.17
      },
      {
        "date": "2019-05",
        "close": 43.77
      },
      {
        "date": "2019-06",
        "close": 49.48
      },
      {
        "date": "2019-07",
        "close": 53.26
      },
      {
        "date": "2019-08",
        "close": 52.19
      },
      {
        "date": "2019-09",
        "close": 55.99
      },
      {
        "date": "2019-10",
        "close": 62.19
      },
      {
        "date": "2019-11",
        "close": 66.81
      },
      {
        "date": "2019-12",
        "close": 73.41
      },
      {
        "date": "2020-01",
        "close": 77.38
      },
      {
        "date": "2020-02",
        "close": 68.34
      },
      {
        "date": "2020-03",
        "close": 63.57
      },
      {
        "date": "2020-04",
        "close": 73.45
      },
      {
        "date": "2020-05",
        "close": 79.49
      },
      {
        "date": "2020-06",
        "close": 91.2
      },
      {
        "date": "2020-07",
        "close": 106.26
      },
      {
        "date": "2020-08",
        "close": 129.04
      },
      {
        "date": "2020-09",
        "close": 115.81
      },
      {
        "date": "2020-10",
        "close": 108.86
      },
      {
        "date": "2020-11",
        "close": 119.05
      },
      {
        "date": "2020-12",
        "close": 132.69
      },
      {
        "date": "2021-01",
        "close": 131.96
      },
      {
        "date": "2021-02",
        "close": 121.26
      },
      {
        "date": "2021-03",
        "close": 122.15
      },
      {
        "date": "2021-04",
        "close": 131.46
      },
      {
        "date": "2021-05",
        "close": 124.61
      },
      {
        "date": "2021-06",
        "close": 136.96
      },
      {
        "date": "2021-07",
        "close": 145.86
      },
      {
        "date": "2021-08",
        "close": 151.83
      },
      {
        "date": "2021-09",
        "close": 141.5
      },
      {
        "date": "2021-10",
        "close": 149.8
      },
      {
        "date": "2021-11",
        "close": 165.3
      },
      {
        "date": "2021-12",
        "close": 177.57
      },
      {
        "date": "2022-01",
        "close": 174.78
      },
      {
        "date": "2022-02",
        "close": 165.12
      },
      {
        "date": "2022-03",
        "close": 174.61
      },
      {
        "date": "2022-04",
        "close": 157.65
      },
      {
        "date": "2022-05",
        "close": 148.84
      },
      {
        "date": "2022-06",
        "close": 136.72
      },
      {
        "date": "2022-07",
        "close": 162.51
      },
      {
        "date": "2022-08",
        "close": 157.22
      },
      {
        "date": "2022-09",
        "close": 138.2
      },
      {
        "date": "2022-10",
        "close": 153.34
      },
      {
        "date": "2022-11",
        "close": 148.03
      },
      {
        "date": "2022-12",
        "close": 129.93
      },
      {
        "date": "2023-01",
        "close": 144.29
      },
      {
        "date": "2023-02",
        "close": 147.41
      },
      {
        "date": "2023-03",
        "close": 164.9
      },
      {
        "date": "2023-04",
        "close": 169.68
      },
      {
        "date": "2023-05",
        "close": 177.25
      },
      {
        "date": "2023-06",
        "close": 193.97
      },
      {
        "date": "2023-07",
        "close": 196.45
      },
      {
        "date": "2023-08",
        "close": 187.87
      },
      {
        "date": "2023-09",
        "close": 171.21
      },
      {
        "date": "2023-10",
        "close": 170.77
      },
      {
        "date": "2023-11",
        "close": 189.95
      },
      {
        "date": "2023-12",
        "close": 192.53
      },
      {
        "date": "2024-01",
        "close": 184.4
      },
      {
        "date": "2024-02",
        "close": 180.75
      },
      {
        "date": "2024-03",
        "close": 171.48
      },
      {
        "date": "2024-04",
        "close": 170.33
      },
      {
        "date": "2024-05",
        "close": 192.25
      },
      {
        "date": "2024-06",
        "close": 210.62
      },
      {
        "date": "2024-07",
        "close": 222.08
      },
      {
        "date": "2024-08",
        "close": 229
      },
      {
        "date": "2024-09",
        "close": 233
      },
      {
        "date": "2024-10",
        "close": 225.91
      },
      {
        "date": "2024-11",
        "close": 237.33
      },
      {
        "date": "2024-12",
        "close": 250.42
      },
      {
        "date": "2025-01",
        "close": 236
      },
      {
        "date": "2025-02",
        "close": 241.84
      },
      {
        "date": "2025-03",
        "close": 222.13
      },
      {
        "date": "2025-04",
        "close": 212.5
      },
      {
        "date": "2025-05",
        "close": 200.85
      },
      {
        "date": "2025-06",
        "close": 205.17
      },
      {
        "date": "2025-07",
        "close": 207.57
      },
      {
        "date": "2025-08",
        "close": 232.14
      },
      {
        "date": "2025-09",
        "close": 254.63
      },
      {
        "date": "2025-10",
        "close": 270.37
      },
      {
        "date": "2025-11",
        "close": 278.85
      },
      {
        "date": "2025-12",
        "close": 271.86
      },
      {
        "date": "2026-01",
        "close": 259.48
      },
      {
        "date": "2026-02",
        "close": 264.18
      },
      {
        "date": "2026-03",
        "close": 253.79
      },
      {
        "date": "2026-04",
        "close": 271.35
      },
      {
        "date": "2026-05",
        "close": 312.06
      },
      {
        "date": "2026-06",
        "close": 295.54
      }
    ]
  },
  {
    "ticker": "KO",
    "name": "The Coca-Cola Company",
    "note": "defensive, low-beta consumer staple",
    "currency": "USD",
    "points": [
      {
        "date": "2016-07",
        "close": 43.63
      },
      {
        "date": "2016-08",
        "close": 43.43
      },
      {
        "date": "2016-09",
        "close": 42.32
      },
      {
        "date": "2016-10",
        "close": 42.4
      },
      {
        "date": "2016-11",
        "close": 40.35
      },
      {
        "date": "2016-12",
        "close": 41.46
      },
      {
        "date": "2017-01",
        "close": 41.57
      },
      {
        "date": "2017-02",
        "close": 41.96
      },
      {
        "date": "2017-03",
        "close": 42.44
      },
      {
        "date": "2017-04",
        "close": 43.15
      },
      {
        "date": "2017-05",
        "close": 45.47
      },
      {
        "date": "2017-06",
        "close": 44.85
      },
      {
        "date": "2017-07",
        "close": 45.84
      },
      {
        "date": "2017-08",
        "close": 45.55
      },
      {
        "date": "2017-09",
        "close": 45.01
      },
      {
        "date": "2017-10",
        "close": 45.98
      },
      {
        "date": "2017-11",
        "close": 45.77
      },
      {
        "date": "2017-12",
        "close": 45.88
      },
      {
        "date": "2018-01",
        "close": 47.59
      },
      {
        "date": "2018-02",
        "close": 43.22
      },
      {
        "date": "2018-03",
        "close": 43.43
      },
      {
        "date": "2018-04",
        "close": 43.21
      },
      {
        "date": "2018-05",
        "close": 43
      },
      {
        "date": "2018-06",
        "close": 43.86
      },
      {
        "date": "2018-07",
        "close": 46.63
      },
      {
        "date": "2018-08",
        "close": 44.57
      },
      {
        "date": "2018-09",
        "close": 46.19
      },
      {
        "date": "2018-10",
        "close": 47.88
      },
      {
        "date": "2018-11",
        "close": 50.4
      },
      {
        "date": "2018-12",
        "close": 47.35
      },
      {
        "date": "2019-01",
        "close": 48.13
      },
      {
        "date": "2019-02",
        "close": 45.34
      },
      {
        "date": "2019-03",
        "close": 46.86
      },
      {
        "date": "2019-04",
        "close": 49.06
      },
      {
        "date": "2019-05",
        "close": 49.13
      },
      {
        "date": "2019-06",
        "close": 50.92
      },
      {
        "date": "2019-07",
        "close": 52.63
      },
      {
        "date": "2019-08",
        "close": 55.04
      },
      {
        "date": "2019-09",
        "close": 54.44
      },
      {
        "date": "2019-10",
        "close": 54.43
      },
      {
        "date": "2019-11",
        "close": 53.4
      },
      {
        "date": "2019-12",
        "close": 55.35
      },
      {
        "date": "2020-01",
        "close": 58.4
      },
      {
        "date": "2020-02",
        "close": 53.49
      },
      {
        "date": "2020-03",
        "close": 44.25
      },
      {
        "date": "2020-04",
        "close": 45.89
      },
      {
        "date": "2020-05",
        "close": 46.68
      },
      {
        "date": "2020-06",
        "close": 44.68
      },
      {
        "date": "2020-07",
        "close": 47.24
      },
      {
        "date": "2020-08",
        "close": 49.53
      },
      {
        "date": "2020-09",
        "close": 49.37
      },
      {
        "date": "2020-10",
        "close": 48.06
      },
      {
        "date": "2020-11",
        "close": 51.6
      },
      {
        "date": "2020-12",
        "close": 54.84
      },
      {
        "date": "2021-01",
        "close": 48.15
      },
      {
        "date": "2021-02",
        "close": 48.99
      },
      {
        "date": "2021-03",
        "close": 52.71
      },
      {
        "date": "2021-04",
        "close": 53.98
      },
      {
        "date": "2021-05",
        "close": 55.29
      },
      {
        "date": "2021-06",
        "close": 54.11
      },
      {
        "date": "2021-07",
        "close": 57.03
      },
      {
        "date": "2021-08",
        "close": 56.31
      },
      {
        "date": "2021-09",
        "close": 52.47
      },
      {
        "date": "2021-10",
        "close": 56.37
      },
      {
        "date": "2021-11",
        "close": 52.45
      },
      {
        "date": "2021-12",
        "close": 59.21
      },
      {
        "date": "2022-01",
        "close": 61.01
      },
      {
        "date": "2022-02",
        "close": 62.24
      },
      {
        "date": "2022-03",
        "close": 62
      },
      {
        "date": "2022-04",
        "close": 64.61
      },
      {
        "date": "2022-05",
        "close": 63.38
      },
      {
        "date": "2022-06",
        "close": 62.91
      },
      {
        "date": "2022-07",
        "close": 64.17
      },
      {
        "date": "2022-08",
        "close": 61.71
      },
      {
        "date": "2022-09",
        "close": 56.02
      },
      {
        "date": "2022-10",
        "close": 59.85
      },
      {
        "date": "2022-11",
        "close": 63.61
      },
      {
        "date": "2022-12",
        "close": 63.61
      },
      {
        "date": "2023-01",
        "close": 61.32
      },
      {
        "date": "2023-02",
        "close": 59.51
      },
      {
        "date": "2023-03",
        "close": 62.03
      },
      {
        "date": "2023-04",
        "close": 64.15
      },
      {
        "date": "2023-05",
        "close": 59.66
      },
      {
        "date": "2023-06",
        "close": 60.22
      },
      {
        "date": "2023-07",
        "close": 61.93
      },
      {
        "date": "2023-08",
        "close": 59.83
      },
      {
        "date": "2023-09",
        "close": 55.98
      },
      {
        "date": "2023-10",
        "close": 56.49
      },
      {
        "date": "2023-11",
        "close": 58.44
      },
      {
        "date": "2023-12",
        "close": 58.93
      },
      {
        "date": "2024-01",
        "close": 59.49
      },
      {
        "date": "2024-02",
        "close": 60.02
      },
      {
        "date": "2024-03",
        "close": 61.18
      },
      {
        "date": "2024-04",
        "close": 61.77
      },
      {
        "date": "2024-05",
        "close": 62.93
      },
      {
        "date": "2024-06",
        "close": 63.65
      },
      {
        "date": "2024-07",
        "close": 66.74
      },
      {
        "date": "2024-08",
        "close": 72.47
      },
      {
        "date": "2024-09",
        "close": 71.86
      },
      {
        "date": "2024-10",
        "close": 65.31
      },
      {
        "date": "2024-11",
        "close": 64.08
      },
      {
        "date": "2024-12",
        "close": 62.26
      },
      {
        "date": "2025-01",
        "close": 63.48
      },
      {
        "date": "2025-02",
        "close": 71.21
      },
      {
        "date": "2025-03",
        "close": 71.62
      },
      {
        "date": "2025-04",
        "close": 72.55
      },
      {
        "date": "2025-05",
        "close": 72.1
      },
      {
        "date": "2025-06",
        "close": 70.75
      },
      {
        "date": "2025-07",
        "close": 67.89
      },
      {
        "date": "2025-08",
        "close": 68.99
      },
      {
        "date": "2025-09",
        "close": 66.32
      },
      {
        "date": "2025-10",
        "close": 68.9
      },
      {
        "date": "2025-11",
        "close": 73.12
      },
      {
        "date": "2025-12",
        "close": 69.91
      },
      {
        "date": "2026-01",
        "close": 74.81
      },
      {
        "date": "2026-02",
        "close": 81.56
      },
      {
        "date": "2026-03",
        "close": 76.05
      },
      {
        "date": "2026-04",
        "close": 78.76
      },
      {
        "date": "2026-05",
        "close": 79.01
      },
      {
        "date": "2026-06",
        "close": 81.09
      }
    ]
  },
  {
    "ticker": "XOM",
    "name": "Exxon Mobil Corporation",
    "note": "inflation-sensitive (energy)",
    "currency": "USD",
    "points": [
      {
        "date": "2016-07",
        "close": 88.95
      },
      {
        "date": "2016-08",
        "close": 87.14
      },
      {
        "date": "2016-09",
        "close": 87.28
      },
      {
        "date": "2016-10",
        "close": 83.32
      },
      {
        "date": "2016-11",
        "close": 87.3
      },
      {
        "date": "2016-12",
        "close": 90.26
      },
      {
        "date": "2017-01",
        "close": 83.89
      },
      {
        "date": "2017-02",
        "close": 81.32
      },
      {
        "date": "2017-03",
        "close": 82.01
      },
      {
        "date": "2017-04",
        "close": 81.65
      },
      {
        "date": "2017-05",
        "close": 80.5
      },
      {
        "date": "2017-06",
        "close": 80.73
      },
      {
        "date": "2017-07",
        "close": 80.04
      },
      {
        "date": "2017-08",
        "close": 76.33
      },
      {
        "date": "2017-09",
        "close": 81.98
      },
      {
        "date": "2017-10",
        "close": 83.35
      },
      {
        "date": "2017-11",
        "close": 83.29
      },
      {
        "date": "2017-12",
        "close": 83.64
      },
      {
        "date": "2018-01",
        "close": 87.3
      },
      {
        "date": "2018-02",
        "close": 75.74
      },
      {
        "date": "2018-03",
        "close": 74.61
      },
      {
        "date": "2018-04",
        "close": 77.75
      },
      {
        "date": "2018-05",
        "close": 81.24
      },
      {
        "date": "2018-06",
        "close": 82.73
      },
      {
        "date": "2018-07",
        "close": 81.51
      },
      {
        "date": "2018-08",
        "close": 80.17
      },
      {
        "date": "2018-09",
        "close": 85.02
      },
      {
        "date": "2018-10",
        "close": 79.68
      },
      {
        "date": "2018-11",
        "close": 79.5
      },
      {
        "date": "2018-12",
        "close": 68.19
      },
      {
        "date": "2019-01",
        "close": 73.28
      },
      {
        "date": "2019-02",
        "close": 79.03
      },
      {
        "date": "2019-03",
        "close": 80.8
      },
      {
        "date": "2019-04",
        "close": 80.28
      },
      {
        "date": "2019-05",
        "close": 70.77
      },
      {
        "date": "2019-06",
        "close": 76.63
      },
      {
        "date": "2019-07",
        "close": 74.36
      },
      {
        "date": "2019-08",
        "close": 68.48
      },
      {
        "date": "2019-09",
        "close": 70.61
      },
      {
        "date": "2019-10",
        "close": 67.57
      },
      {
        "date": "2019-11",
        "close": 68.13
      },
      {
        "date": "2019-12",
        "close": 69.78
      },
      {
        "date": "2020-01",
        "close": 62.12
      },
      {
        "date": "2020-02",
        "close": 51.44
      },
      {
        "date": "2020-03",
        "close": 37.97
      },
      {
        "date": "2020-04",
        "close": 46.47
      },
      {
        "date": "2020-05",
        "close": 45.47
      },
      {
        "date": "2020-06",
        "close": 44.72
      },
      {
        "date": "2020-07",
        "close": 42.08
      },
      {
        "date": "2020-08",
        "close": 39.94
      },
      {
        "date": "2020-09",
        "close": 34.33
      },
      {
        "date": "2020-10",
        "close": 32.62
      },
      {
        "date": "2020-11",
        "close": 38.13
      },
      {
        "date": "2020-12",
        "close": 41.22
      },
      {
        "date": "2021-01",
        "close": 44.84
      },
      {
        "date": "2021-02",
        "close": 54.37
      },
      {
        "date": "2021-03",
        "close": 55.83
      },
      {
        "date": "2021-04",
        "close": 57.24
      },
      {
        "date": "2021-05",
        "close": 58.37
      },
      {
        "date": "2021-06",
        "close": 63.08
      },
      {
        "date": "2021-07",
        "close": 57.57
      },
      {
        "date": "2021-08",
        "close": 54.52
      },
      {
        "date": "2021-09",
        "close": 58.82
      },
      {
        "date": "2021-10",
        "close": 64.47
      },
      {
        "date": "2021-11",
        "close": 59.84
      },
      {
        "date": "2021-12",
        "close": 61.19
      },
      {
        "date": "2022-01",
        "close": 75.96
      },
      {
        "date": "2022-02",
        "close": 78.42
      },
      {
        "date": "2022-03",
        "close": 82.59
      },
      {
        "date": "2022-04",
        "close": 85.25
      },
      {
        "date": "2022-05",
        "close": 96
      },
      {
        "date": "2022-06",
        "close": 85.64
      },
      {
        "date": "2022-07",
        "close": 96.93
      },
      {
        "date": "2022-08",
        "close": 95.59
      },
      {
        "date": "2022-09",
        "close": 87.31
      },
      {
        "date": "2022-10",
        "close": 110.81
      },
      {
        "date": "2022-11",
        "close": 111.34
      },
      {
        "date": "2022-12",
        "close": 110.3
      },
      {
        "date": "2023-01",
        "close": 116.01
      },
      {
        "date": "2023-02",
        "close": 109.91
      },
      {
        "date": "2023-03",
        "close": 109.66
      },
      {
        "date": "2023-04",
        "close": 118.34
      },
      {
        "date": "2023-05",
        "close": 102.18
      },
      {
        "date": "2023-06",
        "close": 107.25
      },
      {
        "date": "2023-07",
        "close": 107.24
      },
      {
        "date": "2023-08",
        "close": 111.19
      },
      {
        "date": "2023-09",
        "close": 117.58
      },
      {
        "date": "2023-10",
        "close": 105.85
      },
      {
        "date": "2023-11",
        "close": 102.74
      },
      {
        "date": "2023-12",
        "close": 99.98
      },
      {
        "date": "2024-01",
        "close": 102.81
      },
      {
        "date": "2024-02",
        "close": 104.52
      },
      {
        "date": "2024-03",
        "close": 116.24
      },
      {
        "date": "2024-04",
        "close": 118.27
      },
      {
        "date": "2024-05",
        "close": 117.26
      },
      {
        "date": "2024-06",
        "close": 115.12
      },
      {
        "date": "2024-07",
        "close": 118.59
      },
      {
        "date": "2024-08",
        "close": 117.94
      },
      {
        "date": "2024-09",
        "close": 117.22
      },
      {
        "date": "2024-10",
        "close": 116.78
      },
      {
        "date": "2024-11",
        "close": 117.96
      },
      {
        "date": "2024-12",
        "close": 107.57
      },
      {
        "date": "2025-01",
        "close": 106.83
      },
      {
        "date": "2025-02",
        "close": 111.33
      },
      {
        "date": "2025-03",
        "close": 118.93
      },
      {
        "date": "2025-04",
        "close": 105.63
      },
      {
        "date": "2025-05",
        "close": 102.3
      },
      {
        "date": "2025-06",
        "close": 107.8
      },
      {
        "date": "2025-07",
        "close": 111.64
      },
      {
        "date": "2025-08",
        "close": 114.29
      },
      {
        "date": "2025-09",
        "close": 112.75
      },
      {
        "date": "2025-10",
        "close": 114.36
      },
      {
        "date": "2025-11",
        "close": 115.92
      },
      {
        "date": "2025-12",
        "close": 120.34
      },
      {
        "date": "2026-01",
        "close": 141.4
      },
      {
        "date": "2026-02",
        "close": 152.5
      },
      {
        "date": "2026-03",
        "close": 169.66
      },
      {
        "date": "2026-04",
        "close": 154.33
      },
      {
        "date": "2026-05",
        "close": 145.26
      },
      {
        "date": "2026-06",
        "close": 140.47
      }
    ]
  },
  {
    "ticker": "JPM",
    "name": "JPMorgan Chase & Co.",
    "note": "rate-sensitive financial",
    "currency": "USD",
    "points": [
      {
        "date": "2016-07",
        "close": 63.97
      },
      {
        "date": "2016-08",
        "close": 67.5
      },
      {
        "date": "2016-09",
        "close": 66.59
      },
      {
        "date": "2016-10",
        "close": 69.26
      },
      {
        "date": "2016-11",
        "close": 80.17
      },
      {
        "date": "2016-12",
        "close": 86.29
      },
      {
        "date": "2017-01",
        "close": 84.63
      },
      {
        "date": "2017-02",
        "close": 90.62
      },
      {
        "date": "2017-03",
        "close": 87.84
      },
      {
        "date": "2017-04",
        "close": 87
      },
      {
        "date": "2017-05",
        "close": 82.15
      },
      {
        "date": "2017-06",
        "close": 91.4
      },
      {
        "date": "2017-07",
        "close": 91.8
      },
      {
        "date": "2017-08",
        "close": 90.89
      },
      {
        "date": "2017-09",
        "close": 95.51
      },
      {
        "date": "2017-10",
        "close": 100.61
      },
      {
        "date": "2017-11",
        "close": 104.52
      },
      {
        "date": "2017-12",
        "close": 106.94
      },
      {
        "date": "2018-01",
        "close": 115.67
      },
      {
        "date": "2018-02",
        "close": 115.5
      },
      {
        "date": "2018-03",
        "close": 109.97
      },
      {
        "date": "2018-04",
        "close": 108.78
      },
      {
        "date": "2018-05",
        "close": 107.01
      },
      {
        "date": "2018-06",
        "close": 104.2
      },
      {
        "date": "2018-07",
        "close": 114.95
      },
      {
        "date": "2018-08",
        "close": 114.58
      },
      {
        "date": "2018-09",
        "close": 112.84
      },
      {
        "date": "2018-10",
        "close": 109.02
      },
      {
        "date": "2018-11",
        "close": 111.19
      },
      {
        "date": "2018-12",
        "close": 97.62
      },
      {
        "date": "2019-01",
        "close": 103.5
      },
      {
        "date": "2019-02",
        "close": 104.36
      },
      {
        "date": "2019-03",
        "close": 101.23
      },
      {
        "date": "2019-04",
        "close": 116.05
      },
      {
        "date": "2019-05",
        "close": 105.96
      },
      {
        "date": "2019-06",
        "close": 111.8
      },
      {
        "date": "2019-07",
        "close": 116
      },
      {
        "date": "2019-08",
        "close": 109.86
      },
      {
        "date": "2019-09",
        "close": 117.69
      },
      {
        "date": "2019-10",
        "close": 124.92
      },
      {
        "date": "2019-11",
        "close": 131.76
      },
      {
        "date": "2019-12",
        "close": 139.4
      },
      {
        "date": "2020-01",
        "close": 132.36
      },
      {
        "date": "2020-02",
        "close": 116.11
      },
      {
        "date": "2020-03",
        "close": 90.03
      },
      {
        "date": "2020-04",
        "close": 95.76
      },
      {
        "date": "2020-05",
        "close": 97.31
      },
      {
        "date": "2020-06",
        "close": 94.06
      },
      {
        "date": "2020-07",
        "close": 96.64
      },
      {
        "date": "2020-08",
        "close": 100.19
      },
      {
        "date": "2020-09",
        "close": 96.27
      },
      {
        "date": "2020-10",
        "close": 98.04
      },
      {
        "date": "2020-11",
        "close": 117.88
      },
      {
        "date": "2020-12",
        "close": 127.07
      },
      {
        "date": "2021-01",
        "close": 128.67
      },
      {
        "date": "2021-02",
        "close": 147.17
      },
      {
        "date": "2021-03",
        "close": 152.23
      },
      {
        "date": "2021-04",
        "close": 153.81
      },
      {
        "date": "2021-05",
        "close": 164.24
      },
      {
        "date": "2021-06",
        "close": 155.54
      },
      {
        "date": "2021-07",
        "close": 151.78
      },
      {
        "date": "2021-08",
        "close": 159.95
      },
      {
        "date": "2021-09",
        "close": 163.69
      },
      {
        "date": "2021-10",
        "close": 169.89
      },
      {
        "date": "2021-11",
        "close": 158.83
      },
      {
        "date": "2021-12",
        "close": 158.35
      },
      {
        "date": "2022-01",
        "close": 148.6
      },
      {
        "date": "2022-02",
        "close": 141.8
      },
      {
        "date": "2022-03",
        "close": 136.32
      },
      {
        "date": "2022-04",
        "close": 119.36
      },
      {
        "date": "2022-05",
        "close": 132.23
      },
      {
        "date": "2022-06",
        "close": 112.61
      },
      {
        "date": "2022-07",
        "close": 115.36
      },
      {
        "date": "2022-08",
        "close": 113.73
      },
      {
        "date": "2022-09",
        "close": 104.5
      },
      {
        "date": "2022-10",
        "close": 125.88
      },
      {
        "date": "2022-11",
        "close": 138.18
      },
      {
        "date": "2022-12",
        "close": 134.1
      },
      {
        "date": "2023-01",
        "close": 139.96
      },
      {
        "date": "2023-02",
        "close": 143.35
      },
      {
        "date": "2023-03",
        "close": 130.31
      },
      {
        "date": "2023-04",
        "close": 138.24
      },
      {
        "date": "2023-05",
        "close": 135.71
      },
      {
        "date": "2023-06",
        "close": 145.44
      },
      {
        "date": "2023-07",
        "close": 157.96
      },
      {
        "date": "2023-08",
        "close": 146.33
      },
      {
        "date": "2023-09",
        "close": 145.02
      },
      {
        "date": "2023-10",
        "close": 139.06
      },
      {
        "date": "2023-11",
        "close": 156.08
      },
      {
        "date": "2023-12",
        "close": 170.1
      },
      {
        "date": "2024-01",
        "close": 174.36
      },
      {
        "date": "2024-02",
        "close": 186.06
      },
      {
        "date": "2024-03",
        "close": 200.3
      },
      {
        "date": "2024-04",
        "close": 191.74
      },
      {
        "date": "2024-05",
        "close": 202.63
      },
      {
        "date": "2024-06",
        "close": 202.26
      },
      {
        "date": "2024-07",
        "close": 212.8
      },
      {
        "date": "2024-08",
        "close": 224.8
      },
      {
        "date": "2024-09",
        "close": 210.86
      },
      {
        "date": "2024-10",
        "close": 221.92
      },
      {
        "date": "2024-11",
        "close": 249.72
      },
      {
        "date": "2024-12",
        "close": 239.71
      },
      {
        "date": "2025-01",
        "close": 267.3
      },
      {
        "date": "2025-02",
        "close": 264.65
      },
      {
        "date": "2025-03",
        "close": 245.3
      },
      {
        "date": "2025-04",
        "close": 244.62
      },
      {
        "date": "2025-05",
        "close": 264
      },
      {
        "date": "2025-06",
        "close": 289.91
      },
      {
        "date": "2025-07",
        "close": 296.24
      },
      {
        "date": "2025-08",
        "close": 301.42
      },
      {
        "date": "2025-09",
        "close": 315.43
      },
      {
        "date": "2025-10",
        "close": 311.12
      },
      {
        "date": "2025-11",
        "close": 313.08
      },
      {
        "date": "2025-12",
        "close": 322.22
      },
      {
        "date": "2026-01",
        "close": 305.89
      },
      {
        "date": "2026-02",
        "close": 300.3
      },
      {
        "date": "2026-03",
        "close": 294.16
      },
      {
        "date": "2026-04",
        "close": 313.23
      },
      {
        "date": "2026-05",
        "close": 299.31
      },
      {
        "date": "2026-06",
        "close": 322.07
      }
    ]
  }
];

export function getAsset(ticker: string): DemoAsset | undefined {
  return DEMO_ASSETS.find((a) => a.ticker === ticker.toUpperCase());
}
